---

- name: Install list of packages
  yum: name={{item}} state=latest
  with_items:
  - httpd

- name: Create directory /run/lock for apache2
  file: path=/run/lock state=directory

- name: Start services
  service: name={{item}} state=started
  with_items:
  - httpd
